# SPDX-License-Identifier: BSD-2-Clause
# Copyright  (c) 2020-2023, The Chancellor, Masters and Scholars of the University
# of Oxford, and the 'Galv' Developers. All rights reserved.

# This docker-compose setup is for local dev purposes only.
# Its role is to connect the backend to a postgres database.

version: "3.8"

services:
  app:
    image: app
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
      - mailhog
    volumes:
      - ./.dev/.static_files:/galv_files/static
      - ./.dev/.media_files:/galv_files/media
      - ./backend_django:/code/backend_django
      - ./.dev/spec:/spec
      # datafiles should be mounted to DATA_ROOT in the container
      # only matters when ALLOW_LOCAL_DATA_STORAGE is enabled
      - ./.dev/datafiles:/galv_files/data
    environment:
      VIRTUAL_HOST: "localhost"
      FRONTEND_VIRTUAL_HOST: "http://${VIRTUAL_HOST_ROOT},https://${VIRTUAL_HOST_ROOT}"
      DJANGO_SETTINGS: "dev"
      DJANGO_SUPERUSER_PASSWORD: "admin"
      AWS_ACCESS_KEY_ID: "AKIAZQ3DU5GQ7Y5V7TFJ"
      DJANGO_AWS_STORAGE_BUCKET_NAME: "galv"
      DJANGO_AWS_S3_REGION_NAME: "eu-west-2"
      # Test local data storage mode by enabling DJANGO_ALLOW_LOCAL_DATA_STORAGE (will override AWS settings for data files)
      DJANGO_ALLOW_LOCAL_DATA_STORAGE: "True"
    env_file:
      - ./.env
      - ./.env.secret
    restart: unless-stopped
    ports:
      - "8001:80"
    # Replace the gnuicorn server with the Django development runserver
    command: "python manage.py runserver 0.0.0.0:8000"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  postgres:
    image: "postgres:14"
    stop_signal: SIGINT                 # Fast Shutdown mode
    volumes:
      - "./.dev/data:/var/lib/postgresql/data"
    environment:
      # variables listed as defaults in backend_django/config/settings_dev.py
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "galv"
      POSTGRES_PORT: "5432"
    restart: unless-stopped

  app_test:
    image: app-test
    build:
      dockerfile: Dockerfile-test
      context: .
    depends_on:
      - postgres
    volumes:
      - ./.test/.static_files:/galv_files/static
      - ./backend_django:/code/backend_django
    environment:
      FRONTEND_VIRTUAL_HOST: "http://localhost"
      VIRTUAL_HOST: "localhost"
      VIRTUAL_HOST_ROOT: "localhost"
      DJANGO_SETTINGS: "dev"
      DJANGO_ALLOW_LOCAL_DATA_STORAGE: "True"
    env_file:
      - ./.env
    restart: "no"

  make_spec:
    image: app-spec
    build:
      dockerfile: Dockerfile-test
      context: .
    volumes:
      - ./.dev/spec:/spec
      - ./backend_django:/code/backend_django
    environment:
      FRONTEND_VIRTUAL_HOST: "http://localhost"
      VIRTUAL_HOST: "localhost"
      VIRTUAL_HOST_ROOT: "localhost"
      DJANGO_SETTINGS: "dev"
    env_file:
      - ./.env
    restart: "no"
    command: "../make_spec.sh"


  check_spec:
    image: openapitools/openapi-diff
    volumes:
      - ./.dev/spec:/spec
    entrypoint: /bin/sh -c
    environment:
      REMOTE_SPEC_SOURCE: "https://github.com/Battery-Intelligence-Lab/galv-spec/releases/latest/download/galv-spec.json"
    command: ["java -jar /app/openapi-diff.jar --fail-on-incompatible --markdown /spec/diff.md $${REMOTE_SPEC_SOURCE} $$(ls /spec/openapi-*.json | tail -n 1)"]

  docs:
    build:
      dockerfile: Dockerfile
      context: ./docs
    volumes:
      - ./docs/source:/source
      - ./docs/build-dev:/build
    ports:
      - "8005:80"
