# fly.toml app configuration file generated for galv-backend-dev-debug on 2023-12-30T07:23:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "galv-backend-dev"
primary_region = "lhr"
console_command = "/code/manage.py shell"

[build]

[deploy]
#  release_command = "/code/fly_setup.sh"

[env]
  PORT = "8000"
  VIRTUAL_HOST = "galv-backend-dev.fly.dev"
  FRONTEND_VIRTUAL_HOST = "http://galv-frontend-dev.fly.dev,https://galv-frontend-dev.fly.dev"
  DJANGO_SETTINGS_MODULE = "config.settings"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/static/"
  url_prefix = "/django_static/"
