name: galv-spec compatibility
on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Setup docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Generate spec
        run: |
          mkdir -p .dev/spec
          sudo chmod 777 .dev/spec
          # app will create a spec file tagged with the version, but we create our own spec for comparison
          # using x rather than a number means it appears later and gets picked up by `tail -n 1` in check_spec
          docker-compose run --rm app bash -c "python backend_django/manage.py spectacular --format openapi-json >> .dev/spec/openapi-x.json"
          sudo chmod 777 .dev/spec/*

      - name: Run spec check
        run: |
          docker-compose run --rm check_spec
