name: OpenAPI spec compatibility
on:
  workflow_run:
    branches:
      - v*.*.*
    tags:
      - v*.*.*
    workflows: [Django test]
    types:
      - completed
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  version:
    uses: Battery-Intelligence-Lab/galv-backend/.github/workflows/get-version.yml@main
    secrets: inherit

  check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || ${{ github.event_name == 'workflow_dispatch' }}
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Check version matches ref
        run: |
          # Assert that the release version matches the branch name
          if [ "${{ needs.version.outputs.version }}" != "${{ github.ref_name }}" ]; then
              echo "Release version ${{ needs.version.outputs.version }} does not match version in tag name ${{ github.ref_name }}"
              exit 1
          fi

      - name: Setup docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          mkdir -p .dev/spec
          sudo chmod 777 .dev/spec

      - name: Generate spec
        run: |
          # using x rather than a number means it appears later and gets picked up by `tail -n 1` in check_spec
          docker-compose run --rm app bash -c "python backend_django/manage.py spectacular --format openapi-json >> /spec/openapi-x.json"
          # Copy spec for upload
          cp .dev/spec/openapi-x.json .dev/spec/openapi-${{ needs.version.outputs.version }}.json

      - name: Run spec check vs prev version
        if: ${{ needs.version.outputs.prev_version != '' && !needs.version.outputs.is_major_release }}
        run: |
          sudo chmod 777 .dev/spec/*
          wget -O .dev/spec/openapi-${{ needs.version.outputs.prev_version }}.json https://raw.githubusercontent.com/Battery-Intelligence-Lab/galv-backend/release/${{ needs.version.outputs.prev_version }}/schema.json
          docker-compose run --rm -e REMOTE_SPEC_SOURCE=.dev/spec/openapi-${{ needs.version.outputs.prev_version }}.json check_spec

      - name: Upload clients
        uses: actions/upload-artifact@v4
        with:
          name: spec
          path: .dev/spec/openapi-${{ needs.version.outputs.version }}.json
          retention-days: 1
