name: Get version

on:
  # reusable workflow
  workflow_call:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
    outputs:
      version:
        description: "API_VERSION defined in settings_base.py"
        value: ${{ jobs.get-version.outputs.version }}
      prev-version-tag:
        description: "Previous version tag"
        value: ${{ jobs.get_version.outputs.prev-version-tag }}
      is-major-release:
        description: "Is this a major release?"
        value: ${{ jobs.get_version.outputs.is-major-release }}
      untagged-release:
        description: "Is this an unreleased version?"
        value: ${{ jobs.get_version.outputs.untagged-release }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.scrape.outputs.version }}
      prev-version-tag: ${{ steps.search.outputs.prev-version-tag }}
      is-major-release: ${{ steps.search.outputs.previous_major_version_tag != steps.search.outputs.prev-version-tag }}
      untagged-release: ${{ steps.search.outputs.untagged-release == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract version
        id: scrape
        run: |
          # Extract release version from settings
          API_VERSION=$(cat backend_django/config/settings_base.py | grep "API_VERSION =" | cut -d'"' -f2)
          # Assert version is valid semver
          if ! [[ "$API_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Release version v$API_VERSION is not valid semver"
              exit 1
          fi
          echo "API_VERSION: v$API_VERSION"
          echo "version=v$API_VERSION" >> $GITHUB_OUTPUT

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.debug_enabled }}

      - name: Search for previous version tag
        id: search
        run: |
          # Get a list of all repository tags
          git fetch --tags --force
          # Create our tag if this is a branch rather than a tag
          UNTAGGED_RELEASE=false
          if [ "${{ github.ref_type }}" == "branch" ]; then
            git config --global user.email gg@example.com
            git config --global user.name "GitHub Actions"
            if [ -z $(git tag --list | grep ${{ steps.scrape.outputs.version }}) ]; then
              UNTAGGED_RELEASE=true
            fi          
            git tag ${{ steps.scrape.outputs.version }} || true
          fi
          echo untagged-release=$UNTAGGED_RELEASE >> $GITHUB_OUTPUT
          
          # Save tag list to a temporary file
          git tag --list > tags.txt
          # Get the previous tag
          python -c "
          import os, re
          with open('tags.txt', 'r') as f:
            tags = f.read().splitlines()
          tags = [tag for tag in tags if re.match(r'^v[0-9]+\.[0-9]+\.[0-9]+$', tag)]
          tags.sort(key=lambda s: list(map(int, s[1:].split('.'))))
          i = tags.index('${{ steps.scrape.outputs.version }}')
          if i == 0:
            os.system('echo prev-version-tag= >> $GITHUB_OUTPUT')
          else:
            os.system(f'echo prev-version-tag={tags[i-1]} >> $GITHUB_OUTPUT')
          # Get the previous major version tag
          if i == 0:
            os.system('echo previous_major_version_tag= >> $GITHUB_OUTPUT')
          else:
            major_version = tags[i].split('.')[0]
            prev_ver_tags = [tag for tag in tags if tag.split('.')[0] < major_version]
            if len(prev_ver_tags) == 0:
                os.system('echo previous_major_version_tag= >> $GITHUB_OUTPUT')
            else:
                os.system(f'echo previous_major_version_tag={prev_ver_tags[-1]} >> $GITHUB_OUTPUT')
          "
          cat $GITHUB_OUTPUT
