name: CI Tests
on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      issue_release:
        type: boolean
        description: 'Issue a release'
        required: false
        default: false
      skip_compatibility_check:
        type: boolean
        description: 'Skip API compatibility check. WARNING: this will allow breaking changes to the API to be released.'
        required: false
        default: false

jobs:
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.check-tag.outputs.match }}
    steps:
      - uses: actions/checkout@v3
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Setup docker-compose
        run: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

      - name: Build container
        run: docker-compose build app_test

      - name: Run tests
        run: docker-compose run --rm app_test

      - name: Validate spec
        run: |
          docker-compose run --rm app_test bash -c "python manage.py spectacular --fail-on-warn --validate"

      - name: Check if tagged release is required
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi

  release:
    needs:
      - run-tests
    if: ${{ needs.run-tests.outputs.release == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.issue_release == 'true') }}
    uses: Battery-Intelligence-Lab/galv-backend/.github/workflows/issue-release.yml@main
    secrets: inherit
    with:
      debug_enabled: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      skip_compatibility_check: ${{ github.event_name == 'workflow_dispatch' && inputs.skip_compatibility_check }}
